apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mediawiki-slave
  labels:
    app: mediawiki
spec:
  selector:
    matchLabels:
      app: mediawiki
      tier: web
  replicas: 2
  template:
    metadata:
      labels:
        app: mediawiki
        tier: web
    spec:
      containers:
      - name: mediawiki-slave
        image: mediawiki:1.31
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379